# Generated by Django 2.1.5 on 2019-02-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squadgoals_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
