# Generated by Django 2.1.5 on 2019-02-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squadgoals_app', '0002_auto_20190225_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('collaborators', models.ManyToManyField(to='squadgoals_app.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Subgoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('isComplete', models.BooleanField(default=False)),
                ('associatedGoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadgoals_app.Goal')),
                ('collaborators', models.ManyToManyField(to='squadgoals_app.AppUser')),
            ],
        ),
    ]
